[pytest]
testpaths = tests

asyncio_default_fixture_loop_scope = session

python_files = test_*.py
python_functions = test_*
python_classes = Test*

log_cli = true
log_cli_level = DEBUG

addopts = -n auto --asyncio-mode=auto
